### PR TITLE
Add default .editorconfig

### PR DESCRIPTION
**Pull request by matijs**
Add a sensible default `.editorconfig` for web based projects.

### CODE REVIEW

**Comment by ianpaschal** [comment]
@ImreBognarUltimaker @ChrisTerBeke

Does this conflict with anything we do in JS/TS/React? I don't think so, right?

**Comment by ChrisTerBeke** [comment]
> @ImreBognarUltimaker @ChrisTerBeke
> 
> Does this conflict with anything we do in JS/TS/React? I don't think so, right?

Doesn't look like it.

**Comment by ImreBognarUltimaker** [comment]
I am not sure if they are the same as our eslint config. Which is not the same in all our repos.

@matijs we do have a code style we agreed upon, not sure if you know about this repo:
https://github.com/Ultimaker/Meta

**Comment by Ghostkeeper** [comment]
That is the repository yhis Pull Request was made on, so I'm sure he knows about it.:wink:

I'll point out that your indent rules for some files specify 2 spaces instead of 4 which is prescribed by our global code style here. I'm not very bothered by it but it might be useful to keep that consistent.

**Comment by ianpaschal** [comment]
> I'll point out that your indent rules for some files specify 2 spaces instead of 4 which is prescribed by our global code style here.

Unfortunately several reasons mean that we have to use 2 in certain places. So these would be overrides. Namely, YML has a hard requirement similar to Python, and while JSON doesn't care about whitespace, 2 is the widely used industry standard within the JavaScript world and thus, always formatted as such by package managers such as NPM and Yarn.

**Comment by matijs** [comment]
Could this be merged? It doesn't have to be set in stone and I'm sure we'll add more exceptions in the future, change our minds or even have good reason to deviate in specific projects.

**Comment by ianpaschal** [comment]
My reason for holding off is that there are actually a bunch of repos from connected services where we use 4 space indentation in JSON.

On the one hand, I'd like to keep each language-specific set of rules as close to the globals as possible.

On the other hand, we shouldn't really write JSON by hand 95% of the time, so it shouldn't really matter.

**Comment by nallath** [comment]
@ianpaschal Yaml supports 4 spaces just fine: _"The suggested syntax for YAML files is to use 2 spaces for indentation, but YAML will follow whatever indentation system that the individual file uses."_

**Comment by matijs** [comment]
I am happy to change the indentation for YAML files to 4 spaces if we already use 4 spaces pretty much everywhere else. If we don't then I propose to merge this and align whenever you come across a file with a different level of indentation.

As for JSON… @ianpaschal any idea why the JSON files in the connected services repos use 4 spaces? Any idea what, if any, tools were used to generate these files?

**Comment by ianpaschal** [comment]
@nallath Huh. TIL. Thanks.

@matijs I don't know off the top of my head. I would have thought Yarn, but I suspect instead that we manually converted all indentation to 4 spaces. Did you get a chance to run the experiment with NPM and Yarn?

**Comment by matijs** [comment]
@ianpaschal npm does not seem to take `.editorconfig` into consideration but once an indentation level is chosen, it honours it, like yarn as you said.

**Comment by ianpaschal** [comment]
OK. In that case let's stick with 4 spaces everywhere.

**Pull request merged**
